# Docker compose to run the php application

services:
  thinkidownloader:
    image: sumeetweb/thinki-php:latest
    container_name: ThinkiDownloader
    volumes:
      - .:/app
    working_dir: /app
    command: php thinkidownloader3.php --json ${COURSE_DATA_FILE}
    environment:
      - COURSE_DATA_FILE=${COURSE_DATA_FILE}
      - CLIENT_DATE=${CLIENT_DATE}
      - COOKIE_DATA=${COOKIE_DATA}
      - VIDEO_DOWNLOAD_QUALITY=${VIDEO_DOWNLOAD_QUALITY}
